### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by McTwist** [McTwist/Blockland-TorqueScript-Lessons#1]
These are the lessons to add. It will be updated with more if required.

- [ ] Datablocks: items, vehicles, light, sound, etc...
- [ ] Math: trigonometry, vectors, rays, trigger box
- [ ] Good-to-know functions: trigonometry, random, vectors, dump, ForceLoadAddOn, Blockland only functions
- [ ] Input: ActionMap, GlobalActionMap
- [ ] Events: input, output
- [ ] Server-client commands: tagged strings, commandToServer, commandToClient
- [ ] GUI: profile, bitmap, examples(button, scrollbar, window, etc)
- [ ] Implementation of common algorithm (sorting, searching, etc)
- [ ] (Advanced) Network: HTTPObject, TCPObject, alternatives
- [ ] (Advanced) TorqueScript quirks: return, strings, arithmetic, [string evals](https://gist.github.com/McTwist/56853ab0f98f2fe00dbcdbe3a6ee9f59#file-clone-cs-L8), echo, etc...
- [ ] (Advanced) Inheritance and hierarchies

And references to several resources that will make it easier for programmers. Post them here and they will be added in some way or another.

**Comment by McTwist** [comment]
Refer to this tutorial for more info: http://docs.garagegames.com/tgea/official/content/documentation/Scripting%20Reference/Introduction/TorqueScript.html
